services:
  arb-sepolia:
    container_name: arb-sepolia
    image: offchainlabs/nitro-node:v3.6.0-fc07dd2
    restart: unless-stopped
    stop_grace_period: 5m
    command:
      --chain.id=421614
      --parent-chain.connection.url=http://geth-sepolia:22545
      --parent-chain.blob-client.beacon-url=http://prysm-sepolia:22500
      --http.api=net,web3,eth
      --http.corsdomain=*
      --http.addr=0.0.0.0
      --http.vhosts=*
      --http.port=22557
      --execution.rpc.gas-cap=10000000000
      --ws.addr 0.0.0.0
      --ws.port=22558
      --ws.origins=*
      --init.latest=pruned
    volumes:
      - ./arb-data:/home/user/.arbitrum
    ports:
      - 22557:22557 # json-rpc endpoint
      - 22558:22558 # ws endpoint
    networks:
      - cnid

networks:
  cnid:
    external: true